#!/usr/bin/python
#coding:utf-8
import paramiko

def machinInfo(ip,name,pwd,command):
    ssh=paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(hostname=ip,port=22,username=name,password=pwd)
    stdin,stdout,stderr=ssh.exec_command(command)
    result=stdout.readlines()
    return result